package cardiac_diseases;

public enum Disease {
    ASCENDING_AORTIC_ANEURYSM, DESCENDING_AORTIC_ANEURYSM, ABDOMINAL_ANEURYSM, ARRYTHMIAS, CARDIAC_TAMPONADE,
    DILATED_CARDIOMYOPATHY, HYPERTROPHIC_CARDIOMYOPATHY, RESTRICTIVE_CARDIOMYOPATHY, CONGENITAL_DEFECTS,
    INTERAURICULAR_COMMUNICATION, AORTIC_COARCTATION, ARTERY_CONDUCT_PERSISTENCY, FALLOT_TETRALOGY, MAJOR_ARTERY_TRANSPOSITION,
    CORONARY_ARTERIOPATHY, DEEP_VEIN_THROMBOSIS, ENDOCARDITIS,  LEFT_HEART_FAILURE, RIGHT_HEART_FAILURE,
    HYPERTENSION, MITRAL_VALVE_PROLAPSE, MYOCARDIAL_INFARCTION, MYOCARDYTIS, PERICARDITIS, RAYNAUD_DISEASE, REUMATIC_HEART_FAILURE,
    COMPENSATORY_CRASH, PROGRESSIVE_CRASH, IRREVERSIBLE_CRASH, MITRAL_STENOSIS, MITRAL_INSUFICIENCY,
    AORTIC_INSUFICIENCY, AORTIC_STENOSIS, PULMONAR_STENOSIS, VARICOSE_VEINS, TEST
}