package cardiac_diseases;

public enum Symptom {
    CHEST_PAIN, SCAPULA_PAIN, LOWER_BACK_PAIN, ABDOMINAL_PAIN, HOARSENES,
    BRADYCHARDIA, MURMUR_AORTIC_REGURGITATION, DYASTOLIC_MURMUR_AORTA, SYSTOLIC_MURMUR_AORTA, HYPERSENSIBILITY_DEEP_PALPITATION,
    PERICARDIAL_FRICTION_RUB, DIFFERENT_DENSITY_RIGHT_LEFT_PULSE, DIFFERENT_ARTERIAL_PRESSURE_ARMS, DISTENDED_JUGULAR_VEINS, DYSPNEA,
    ORTHOPNEA, TACHYPNEA, STRIDOR, DYSPHAGIA, DRY_COUGH, COUGH,
    PULSATING_MASS_PERIUMBILICAL_AREA, HYPOTENSION, DIZZINESS, SYNCOPE, WEAKNESS,
    COLD_SKIN, STICKY_SKIN, DIAPHORESIS, CYANOSIS, ALTERED_CONSCIOUSNESS, DECREASES_URINARY_OUTPUT, PALPITATIONS,
    HIGH_CENTRAL_VENOUS_PRESSURE, PARADOXIC_PULSE, ANXIETY, WEAK_PULSE,
    TACHYCARDIA, PERIPHERAL_EDEMA, FATIGUE, WEIGHT_GAIN, NASAL_CONGESTION, NAUSEA, VOMITING,
    ABDOMINAL_DISTENSION, STRONG_PULSE, INCREASED_PULMONARY_VENOUS_PRESSURE, DECREASED_CARDIAC_OUTPUT,
    DECREASED_SYSTOLIC_VOLUME, DECREASED_SYSTOLIC_FRACTION, DECREASED_LEFT_VENTRICULAR_VOLUME,
    ACROPACHY, PALPABLE_PULSATION_PULMONARY_ARTERY, DYASTOLIC_SNAP, SYSTOLIC_SNAP,
    CLAUDICATION, HYPERTENSION, HEADACHE, VERTIGO, EPISTAXIS, DECREASED_FEMORAL_PULSE,
    INCREASED_UPPER_EXTREMITY_PULSE, FASTER_THORAX_UPPER_BODY_DEVELOPMENT, RESPIRATORY_DISTRESS_INFANTS,
    GIBSON_MURMUR, THRILL_LEFT_ESTERNAL_SIDE, PROMINENT_LEFT_VENTRICULAR_PULSE, CORRIGAN_PULSE, SLOW_MOTOR_DEVELOPMENT,
    STUNTED_GROWTH, SYSTOLIC_MURMUR, STRONG_SYSTOLIC_MURMUR, RIGHT_VENTRICULAR_IMPULSE,
    PROMINENT_LOWER_ESTERNUM, HEPATOMEGALY, CARDIOMEGALY, HYPOXEMIA, COLD_EXTREMITIES, XANTHELASMA,
    PAIN_GENERAL, PALPABLE_VEIN, VISIBLE_SUPERFICIAL_VEINS, FEVER, SHIVERS, NIGHT_SWEATS,
    ANOREXIA, WEIGHT_LOSS, ARTHRALGIA, VALVE_REGURGITATION, REGURGITATION_MURMUR, HEMATURIA, PIURIA, NUMBNESS, APHASIA,
    PAROXYSMAL_NOCUTURNAL_DYSPNEA, RALES, HEMOPTYSIS, HEART_SOUND_S3, HEART_SOUND_S4, HEPATOJUGULAR_REFLUX, SWELLING, EDEMA, ASCITES,
    BLURRY_VISION, NOCTURIA, LATE_SYSTOLIC_MURMUR, MIDSYSTOLIC_CLICK, ARRHYTHMIA, DEPRESSION,
    PANIC_ATTACKS, CHEST_PRESSURE, HYPERVENTILATION, LETHARGY, PAIN_LEFT_ARM, NECK_PAIN, JAW_PAIN,
    PALE_EXTREMITIES, SWEAT, THORAX_INFLAMMATION, S3_S4_GALLOP, MITRAL_REGURGITATION_MURMUR, PULMONAR_CONGESTION,
    DISTANT_CARDIAC_NOISES, PALENESS, ASCITIS, LIQUID_RETENTION, KUSSMAUL_SIGN, PALE_FINGERS_COLD_STRESSED, COLD,
    THROBBING_DULL_PAIN, TINGLING, TROPHIC_CHANGES_ISCHEMIA, POLIARTRITIS, MARGINAL_ERYTHEMA, SUBCUTANEOUS_NODULES,
    COREA, PREVIOUS_STREPTOCOCCAL_INFECTION, CHEYNE_STOKES_BREATHING, CREPITATIONS, AURICULAR_FIBRILATION,
    HIGH_DIASTOLIC_R1, ANGINA, PULMONAR_EDEMA, R2_R3_EXCISION, APICAL_REMIT, QUINCKE_SIGN, BISFERENS_PULSE,
    DYASTOLIC_MURMUR_LEFT_ESTERNAL_SIDE, R3, R4, SYSTOLIC_REMIT, R2_SPLITING, DILATED_VEINS_CALVES_ANKLES, EDEMA_CALVES_ANKLES,
    HEAVY_LEGS_NIGHT_HOT_WEATHER, LEG_PAIN_STANDING_LONG_WALKS, MENSTRUAL_PAIN

}
